/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'HeadsUpPokerEIP712', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeadsUpPokerEIP712__factory>
getContractFactory(name: 'HeadsUpPokerEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeadsUpPokerEscrow__factory>
getContractFactory(name: 'HeadsUpPokerReplay', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HeadsUpPokerReplay__factory>
getContractFactory(name: 'PokerEvaluatorTest', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PokerEvaluatorTest__factory>

  getContractAt(name: 'HeadsUpPokerEIP712', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeadsUpPokerEIP712>
getContractAt(name: 'HeadsUpPokerEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeadsUpPokerEscrow>
getContractAt(name: 'HeadsUpPokerReplay', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HeadsUpPokerReplay>
getContractAt(name: 'PokerEvaluatorTest', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PokerEvaluatorTest>

  deployContract(name: 'HeadsUpPokerEIP712', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeadsUpPokerEIP712>
deployContract(name: 'HeadsUpPokerEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeadsUpPokerEscrow>
deployContract(name: 'HeadsUpPokerReplay', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeadsUpPokerReplay>
deployContract(name: 'PokerEvaluatorTest', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PokerEvaluatorTest>

  deployContract(name: 'HeadsUpPokerEIP712', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeadsUpPokerEIP712>
deployContract(name: 'HeadsUpPokerEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeadsUpPokerEscrow>
deployContract(name: 'HeadsUpPokerReplay', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HeadsUpPokerReplay>
deployContract(name: 'PokerEvaluatorTest', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PokerEvaluatorTest>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  