// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

error CommitDuplicate(uint8 slot);
error CommitWrongChannel(uint8 slot);
error CommitWrongSignerA(uint8 slot);
error CommitWrongSignerB(uint8 slot);
error CommitUnexpected(uint8 slot);

error NotFinalized();
error PaymentFailed();
error NoBalance();
error ChannelExists();
error BadOpponent();
error InvalidMinSmallBlind();
error NoDeposit();
error NoChannel();
error NotOpponent();
error AlreadyJoined();
error AlreadyFinalized();
error DepositExceedsOpponent();
error ShowdownInProgress();
error NotPlayer();
error SignatureLengthMismatch();
error CardsLengthMismatch();
error CardSaltsLengthMismatch();
error NoOverlap();
error HashMismatch();
error ChannelNotReady();
error BadRoleIndex();
error SequenceTooLow();
error Expired();
error NoShowdownInProgress();
error StillRevealing();
error OpponentHoleOpenFailed();
error InitiatorHolesRequired();
error ActionSignatureLengthMismatch();
error ActionWrongChannel();
error ActionWrongHand();
error ActionInvalidSender();
error ActionWrongSigner();
error NoActionsProvided();
error DisputeInProgress();
error NoDisputeInProgress();
error DisputeStillActive();
error SequenceTooShort();
error SequenceNotLonger();
error GameNotStarted();
error DeckHashMismatch();
error GameAlreadyStarted();
error PeekInProgress();
error NoPeekInProgress();
error PeekNotExpired();
error PeekAlreadyServed();
error PeekWrongStage();
error InvalidDecryptedCard();
error PrerequisitesNotMet();
error RevealAlreadySubmitted();
error InvalidDeck();
error InvalidUnencryptedCard();
error InvalidGameState();
error NotEscrow();
error HelpersNotConfigured();
error HelpersAlreadyConfigured();
error ChannelDeadlineExpired();
error ChannelDeadlineInactive();
error ChannelDeadlineStillActive();
