/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HeadsUpPokerEIP712 } from "./HeadsUpPokerEIP712";
export type { HeadsUpPokerEscrow } from "./HeadsUpPokerEscrow";
export * as factories from "./factories";
export { HeadsUpPokerEIP712__factory } from "./factories/HeadsUpPokerEIP712__factory";
export { HeadsUpPokerEscrow__factory } from "./factories/HeadsUpPokerEscrow__factory";
